commonLabels:
  label-for: faizal-nginx-label

replicaCount: 1

image:
  repository: bitnami/nginx
  tag: latest
  
ingress:
  enabled: true
  pathType: Prefix
  hostname: faizal.sctp-sandbox.com
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    external-dns.alpha.kubernetes.io/hostname: "faizal.sctp-sandbox.com"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  ingressClassName: "nginx"
  tls: true