apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alfatah-nginx-webapp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/al-fatah/argocd-demo-alfatah.git
    targetRevision: HEAD
  destination:
    namespace: alfatah-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true