apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: andre-guestbook
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/andremarkcorray/guestbook-andre.git
    targetRevision: main
    path: .
  destination:
    namespace: andre-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
