apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: group4-nginx-webapp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: applications/
    repoURL: https://github.com/growfatlikeme/argocd-demo_growfat
    targetRevision: HEAD
  destination:
    namespace: group4
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true