apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hanna-nginx-webapp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: manifests/nginx-webapp
    repoURL: https://github.com/hannamatheos/argocd-demo-2
    targetRevision: HEAD
  destination:
    namespace: hanna-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
