apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: indy-guestbook
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/lostsockpuppet/argo-cicd.git
    targetRevision: main
    path: manifest
  destination:
    namespace: indy-ns
    server: "https://kubernetes.default.svc"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true