apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jibin-nginx-webapp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: .
    repoURL: https://github.com/jbttt/argocd-demo.git
    targetRevision: HEAD
  destination:
    namespace: jibin-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true