apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: olivia-guestbook
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/oliviasyhspm/CE12M3L14-guestbook-manifests.git
    targetRevision: main
    path: .
  destination:
    namespace: olivia-guestbook-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
