apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sridhar-nginx-webapp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/sridharmaroju/Manifest-guestbook.git
    targetRevision: HEAD
  destination:
    namespace: sridhar-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true