apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vimal-guessbook-webapp
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: guestbook
    repoURL: https://github.com/vimalkaur1981/guestbook-app.git
    targetRevision: HEAD
  destination:
    namespace: vimal-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true