apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wilson-guestbook
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/wilsonoon2/guestbook.git
    targetRevision: HEAD
    path: .
  destination:
    namespace: wilson-guestbook-ns
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true

