apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: zc-guestbook

spec:
  project: default

  source:
    repoURL: https://github.com/leizichao/zc-guestbook.git
    targetRevision: main
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: zc-ns

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true