replicaCount: 1

image:
  registry: docker.io
  repository: bitnami/nginx

service:
  type: ClusterIP
  ports:
    http: 80

resourcesPreset: nano

ingress:
  enabled: false

cloneStaticSiteFromGit:
  enabled: false