apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-hello
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: hello
  template:
    metadata:
      labels:
        deployment: hello
    spec:
      containers:
      - name: hello
        image: alpine:latest
        command: ["sh", "-c", "echo Hello ${MESSAGE}! && sleep 3600"]
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: http-hello-cm
              key: message